### ISSUE TITLE
Я можно считать облегчил твой код

### ISSUE THREAD

**Issue by ImmortalNameless** [yan4ikyt/webhack#15]
Крч, выкатил обнову на твой код. Убрал все эти ненужные ifы.
Скачать можешь здесь: [ТЫК](https://mega.nz/file/VBxyCCBa#WU1ZmB6LJN-d4ZhAD0kiSAsXgmuF-sEPE6ndiaN8VCg) 
Потом допишешь под себя. Я не стал писать в своем коде заставку и тд.

**Comment by yan4ikyt** [comment]
Спасибо за работу!
