### ISSUE TITLE
I got a problem

### ISSUE THREAD

**Issue by Im-good-person-4-u** [yan4ikyt/webhack#3]
Traceback (most recent call last):
  File "WebHack.py", line 3, in <module>
    eval(compile(base64.b64decode(dontsink),'','exec'))             File "", line 6, in <module>                                      File "", line 7, in <module>
  File "", line 18, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)                   File "/data/data/com.termux/files/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)                               File "/data/data/com.termux/files/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())               File "/data/data/com.termux/files/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ghost** [comment]
I have this problem too...

**Comment by noartem** [comment]
The script is written in python2, but you're running it by python3.8. Just use python2

**Comment by Im-good-person-4-u** [comment]
Well i runned it with python2 and....i got that
$ python2 WebHack.py
Traceback (most recent call last):                                                        File "WebHack.py", line 3, in <module>
    eval(compile(base64.b64decode(dontsink),'','exec'))
  File "", line 6, in <module>

  File "", line 7, in <module>                                                          
  File "", line 333
    f.write(f'{findip}' + '\n')                                                                               ^
SyntaxError: invalid syntax

**Comment by noartem** [comment]
Oh fuck, this code is too bad. You can use instead script from my pull request (#4)

**Comment by MrBuku95** [comment]
It gives me an error, please help.
python3 WebHack.py
  File "WebHack.py", line 673
    programm!--
    ^
IndentationError: unexpected indent
